mod dense_spectral;
mod equilibration;
mod estimation;
mod filter_design;
mod gramians_hsvd;
mod home;
mod identification;
mod linear_solvers;
mod lti;
mod lti_gallery;
mod nonlinear_estimation;
mod pid_design;
mod process_model_fit;
mod reduction;
mod savgol_design;
mod sparse_cholesky;
mod synthesis;

pub use dense_spectral::DenseSpectralDecompositionPage;
pub use equilibration::EquilibrationPage;
pub use estimation::EstimationPage;
pub use filter_design::FilterDesignPage;
pub use gramians_hsvd::GramianHsvdPage;
pub use home::HomePage;
pub use identification::IdentificationPage;
pub use linear_solvers::LinearSolverComparisonPage;
pub use lti::LtiProcessModelsPage;
pub use lti_gallery::LtiPlotGalleryPage;
pub use nonlinear_estimation::NonlinearEstimationPage;
pub use pid_design::PidDesignPage;
pub use process_model_fit::ProcessModelFitPage;
pub use reduction::ReductionPage;
pub use savgol_design::SavGolDesignPage;
pub use sparse_cholesky::SparseCholeskyPage;
pub use synthesis::SynthesisPage;
