mod estimation;
mod filter_design;
mod home;
mod identification;
mod lti;
mod lti_gallery;
mod nonlinear_estimation;
mod pid_design;
mod process_model_fit;
mod reduction;
mod synthesis;

pub use estimation::EstimationPage;
pub use filter_design::FilterDesignPage;
pub use home::HomePage;
pub use identification::IdentificationPage;
pub use lti::LtiProcessModelsPage;
pub use lti_gallery::LtiPlotGalleryPage;
pub use nonlinear_estimation::NonlinearEstimationPage;
pub use pid_design::PidDesignPage;
pub use process_model_fit::ProcessModelFitPage;
pub use reduction::ReductionPage;
pub use synthesis::SynthesisPage;
