name: Rust

on:
  pull_request:
    branches: [ "*" ]
  workflow_call:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Format
      run: cargo fmt --check --verbose
    - name: Lint
      run: cargo clippy --features=std
    - name: Run tests
      run: cargo test --features=std --verbose
    - name: Run tests with mul_add
      run: cargo test --features=std,fma --verbose
